### ISSUE TITLE
Unable to load asset: 

### ISSUE THREAD

**Issue by yanashenyang** [RoadTripMoustache/avatar_maker#11]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "packages/fluttermoji/attributeicons/hair.svg".
The asset does not exist or has empty data.
#0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:324:9)
<asynchronous suspension>
#1      SvgLoader._load.<anonymous closure> (package:flutter_svg/src/loaders.dart:153:41)
<asynchronous suspension>
#2      _VectorGraphicWidgetState._loadPicture.<anonymous closure> (package:vector_graphics/src/vector_graphics.dart:355:40)
<asynchronous suspension>
#3      _VectorGraphicWidgetState._loadPicture.<anonymous closure> (package:vector_graphics/src/vector_graphics.dart:369:13)
<asynchronous suspension>

**Comment by Adaendra** [comment]
Hi @yanashenyang 

We are currently refactoring the code and clearly the actual version *(0.0.0)* is a temporary one. The pull request with all the refactoring and the new documentation will be open in a few minutes, and I hope my collegue won't take too much time to review it. *(But the refactoring is quite big)*

So thanks to use avatar_maker, and I will keep you in touch once the update will be made.

Have a nice day

**Comment by Adaendra** [comment]
Hi @yanashenyang 

The v0.1.0 is now available. As you can see if you start the example, it works quite well.
Give us an heads up if you still have issues.

Have a nice day

**Comment by yanashenyang** [comment]
Thanks for your reply
It works well
Have a nice day
